# -*- coding: utf-8 -*-
"""Assement1_PYTHON_Nivetta.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EnakkR8i6_8tHEAbtCUMY80r_sbiAEzM
"""

# Q1
def area_rect(length,width):
  return length*width

l = float(input('Enter the length of rectangle: '))
w = float(input('Enter the width of rectangle: '))
area_rect(l,w)

#Q2
def BMI_Calc(wt,ht):
  return (wt/(ht**2))
ht = float(input('Enter height in (m): '))
wt = float(input('Enter weight in (kgs): '))
BMI_Calc(wt,ht)

#Q3
student_dict = {}
n = int(input('How many students? '))
for i in range(n):
  x = input('Enter student Name: ')
  y = input('Enter score: ')
  student_dict[x] = y
print(student_dict)

#Q4
age = int(input('Enter age: '))
if age<=18:
  print('Minor')
elif age>18 and age<60:
  print('Adult')
else:
  print('Senior')

#Q5
for i in range(51):
  if i%2 == 0:
    print(i, end = " ")
  else:
    continue

# Q6
credentials = {}
n = int(input('How many users? '))
for i in range(n):
  name_user = input('Enter Name: ')
  passwor_use = input('Enter password: ')
  credentials[name_user] = passwor_use
while True:
  u_name = input('Enter your username: ')
  u_pwd = input('Enter your password: ')
  if credentials[u_name] != u_pwd:
    print('Aunthentication failed, Try again')
    continue
  else:
    print('Correct')
    break

#Q7
import statistics
def calc_avg(num_list):
  print(statistics.mean(user_list))
n = int(input('Enter how many number you want to calculate average for: '))
user_list = [float(input('Enter a value: ')) for x in range(n)]
calc_avg(user_list)

# Q8
def vowel_cnt(user_input):
  vowel_cnt = 0
  for i in user_str:
    if i in 'aeiou':
      vowel_cnt+=1
    else:
      continue
  print(vowel_cnt)
user_str = input('Enter a string: ')
vowel_cnt(user_str)

# Q9
import datetime
print("Today's date and time is: ",datetime.datetime.today())

# Q10
def add_fn(n1,n2):
  try:
    if type(n1) == str or type(n2) == str :
      raise ValueError("Can't add strings!!")
    else:
      return n1+n2
  except ValueError as e:
    print(e)

add_fn(3,4)
add_fn("hi",6)

# Q11
try:
  user_input = int(input("Enter a int value: "))
except ValueError as e:
  print("You cant enter anything other than integers!!")

# Q12
def div_fun(a,b):
  try:
    res = a/b
    if b == 0:
      raise ZeroDivisionError
    else:
      return res
  except ZeroDivisionError as e:
    print("Warning!",e)
div_fun(3,0)

# Q13
def creat_file():
  with open(r"C:\Users\nivetta.t.lv\Downloads\text_files_py\tests1.txt","x") as newfileobj:
    newfileobj.write("Hello,Python!")
creat_file()

# Q14
def read_file():
    with open(r"C:\Users\nivetta.t.lv\Downloads\text_files_py\tests1.txt","r") as readfileobj:
      content = readfileobj.read()
      print(content)
read_file()

# Q15
def appnd():
  with open(r"C:\Users\nivetta.t.lv\Downloads\text_files_py\tests1.txt","a") as file:
    file.write("Python is a great language!")
  with open(r"C:\Users\nivetta.t.lv\Downloads\text_files_py\tests1.txt","r") as r_file:
    cont = r_file.read()
    print(cont)
appnd()