# -*- coding: utf-8 -*-
"""LVADSUSR101-Nivetta-IA2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SfyabHvW0pgJtsARZDr7jgOtQzqwAtsI
"""

from re import I
import pandas as pd
import numpy as np
# Q1
# assuming data is given and stored as np array called data
for i,j,k in np.nditer():
  r = i*.289
  g = j*.56
  b = .114*k
print((r,g,b))

# Q2
mean_val = np.mean()
std_val = np.std()

# Q3
# creating 3d array
sensor_data = np.arange(27).reshape(3,3,3)
print(sensor_data)
print('\n')
# flattening to 1d array
print(sensor_data.flatten())

# Q4
Athletes_2d = np.array([[100,30,20,60,600],[100,30,20,50,30],[100,80,20,50,160],[100,30,20,50,609]])
print(Athletes_2d)
Athletes_2d = Athletes_2d.astype('int')
first_last_1 = Athletes_2d[0,4] - Athletes_2d[0,0]
print('The diff for ath1 is: ',first_last_1)
two = Athletes_2d[1,4] - Athletes_2d[1,0]
print('The diff for ath2 is: ',two)
three= Athletes_2d[2,4] - Athletes_2d[2,0]
print('The diff for ath3 is: ',three)
four = Athletes_2d[3,4] - Athletes_2d[3,0]
print('The diff for ath4 is: ',four)

# Q5
students_2d = np.array([['40','59','55','67','80'],[100,30,20,'Exempt',60],[100,30,20,50,60],[100,'Exempt',20,50,60],[100,30,20,50,60]])
print(students_2d)
df = pd.DataFrame(students_2d)
print('\n')
print(df)
last_3 = df.iloc[:,2:]
print('\n')
print(last_3)
print('\n')
avg_val = last_3.mean()
print(avg_val)

# Q6
weather_2d = np.array([[100,30,20],[100,30,12],[20,50,60],[100,30,60]])
print(weather_2d)
adj = [10,100,1000]
adj_mul = weather_2d*adj
print("\n")
print(adj_mul)

# Q7
data = {'Name':['Alice','Bob','Charlie','David','Eve','Frank','Grace'],
                 'Age':[25,30,35,40,45,50,55],
                 'City': ['NEW YORK','LOS ANGELES','CHICAGO','HOUSTON','PHOENIX','MIAMI','BOSTON'],
                  'Department' : ['HR','IT','Finance','Marketing','Sales','IT','HR']}
df = pd.DataFrame(data)
print(df)
print('\n')
cond = (df.Age<45) & (df.Department != 'HR')
sltd = df[cond]
print(sltd.loc[:,['Name','City']])

# Q8
data = {'Product':['Apple','Banana','Cherry','Dates','ElderBerry','Flour','Grapes'],
                 'Category':['Fruit','Fruit','Fruit','Fruit','Fruit','Bakery','Fruit',],
                 'Price': [1.2,.5,3,2.5,4,1.5,2],
                  'Promotion' : ['True','False','True','True','False','True','False']}
df = pd.DataFrame(data)
print(df)
print('\n')
avg_cat_price = df.groupby('Category')['Price'].mean()
print(avg_cat_price)
print('\n')
cond = (df.Category == 'Fruit') & (df.Promotion == 'False') & (df.Price>avg_cat_price['Fruit'])
selected = df[cond]
print(selected)

# Q9
import pandas as pd
Employee_data = {'Employee':['Alice','Bob','Charlie','David'],
                 'Department':['HR','IT','Finance','IT'],
                 'Manager': ['John','Rachel','Emily','Rachel']}
data_e = pd.DataFrame(Employee_data)
print(data_e)
project_data = {'Employee': ['Alice','Charlie','Eve'],
                'Project':['P1','P3','P2']}
data_p = pd.DataFrame(project_data)
print('\n')
print(data_p)
merged_data = pd.merge(data_e,data_p,on = 'Employee', how = 'left')
print('\n')
print(merged_data)

# Q10
data = {'Department':['ELectronics','ELectronics','Clothing','Clothing','Home Goods'],
        'Salesperson': ['Alice','Bob','Charlie','David','Eve'],
        'sales' : [70000,50000,30000,40000,60000]}
df = pd.DataFrame(data)
print(df,end='\n')
print("\n")
grpd_data = df.groupby(['Department','Salesperson'])['sales'].mean()
print(grpd_data)