# -*- coding: utf-8 -*-
"""LVADSUSR101-Nivetta-FA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LAFLMQJt4bHbJMU0sBAtnr7XEmaNlFOt
"""

import numpy as np
import pandas as pd

# Q1
df = pd.read_excel('/content/Walmart_Dataset Python_Final_Assessment.xlsx')
df.head()
print('The number of rows in the datset is: ',df.shape[0])
print('The number of columns in the datset is: ',df.shape[1])
df.dtypes
df.info()
df.describe()

# Q2 Data cleaning
missing_values = df.isnull().sum()
print(missing_values)
df.dropna(inplace=True)
df.duplicated().sum()
df.drop_duplicates(inplace=True)
# Insights: No duplicates or missing values found in the DS

# Q3 Descriptive statistics
# all the values calculated below analyse the numerical variables central temdacy, deviations, most repeated and range of values.
df.describe()
# insights: There are only 3 numerical columns in the dataset: Sales, Quantity and Profit.
# '''We can see that the average profit is 34 (rounded value) and the mean quantity sold is 3.8 and sales is 226'''

# Total Profit by Geography
profit_by_geo = df.groupby('Geography')['Profit'].sum().reset_index()
print(profit_by_geo)
profit_by_geo['Profit'].sort_values()[::-1].reset_index()
# insight: United States,Los Angeles,California has the largest profit

# Total sales by Geo
Sales_by_geo = df.groupby('Geography')['Sales'].sum().reset_index()
print(Sales_by_geo)
Sales_by_geo['Sales'].sort_values()[::-1].reset_index()
# insight: United States,Los Angeles,California has the largest sales

# Total Quantities sold by Geo
Qty_by_geo = df.groupby('Geography')['Quantity'].sum().reset_index()
print(Qty_by_geo)
Qty_by_geo['Quantity'].sort_values()[::-1].reset_index()
# insight: United States,Los Angeles,California has the largest sales

for i in ['Sales','Profit','Quantity']:
  print(f'The mode of {i} is: {round(df[i].mode(),2)}')
  print(f'The standar deviation of {i} is: {round(df[i].std(),2)}')
  print(f'The variance of {i} is: {round(df[i].var(),2)}')
  print(f'The range of {i} is: {(df[i].max())-df[i].min()}')

df.loc[80,'Geography'] # used to calcualte insights

# Q4 Visualize numerical column value distribution:
colors = sns.color_palette('husl',3)
for j,i in enumerate(['Sales', 'Profit','Quantity']):
  plt.hist(df[i], bins=20, color=colors[j], edgecolor='black')
  plt.xlabel(i)
  plt.ylabel('Frequency')
  plt.title(f'{i} Distribution')
  plt.show()
  # insights: sales is distributed from 0 to 3700. majority of the values lying in the first bun of 0 to 100
  # Profit:There are a few products which have yielded negative profit but the majority has yieled in a positive profit ranging from 0 t0 1500
  # Most of the products sold were sold in the 2 quantity category. From this we can deduce thatbulk orders were not placed

df.columns
sns.scatterplot(x = df['Sales'], y=df['Quantity'], hue = df['Profit'], palette='husl')
# the most sales is generated from tables ans storage yielding in progit of 5k
sns.scatterplot(x = df['Profit'], y=df['Quantity'], hue = df['Category'], palette='husl')
sns.scatterplot(x = df['Profit'], y=df['Quantity'], hue = df['Category'], palette='husl', legend = 'auto')

grpd = df.groupby('Category')['Product Name'].count()
grpd.plot(kind = 'bar', color = 'g', title = 'Category count', ylabel='count')

# insights: The category which has the most number of products is binders followed by papers

category_count = df.Category.value_counts()
category_count_df = pd.DataFrame(category_count)
category_count_df
colors = sns.color_palette('husl',10)
plt.figure(figsize = (10,7))
category_count_df['Category'].plot(kind='line', figsize=(8, 4), title='Category',color = colors[1])
plt.figure(figsize = (10,10))
category_count_df['Category'].plot(kind='pie', labels=df.Category, autopct='%1.1f%%', startangle=140, colors=colors)
plt.title('Count of products sold in each category')
# insights: from the line chart we can deduce the most and least purchased products and stock accordingls. Binders furnishing and storage seem to be performing the best

# Q5: Explore correlations:
import seaborn as sns
correlation_matrix = df.corr()
sns.heatmap(correlation_matrix, annot = True, cmap = 'viridis')
# insights: sales, quantity and profit are very closely correlated

sns.pairplot(df, palette = 'husl', hue='Profit')
# insights : the plots shows how each pair is related to ech other. pairplots are used prevalently in bivariate analysis

# Q6 anamoly detection
for i in ['Sales','Profit','Quantity']:
  sns.boxplot(x=df[i],palette='husl')
# Insights: There are a few anomalies in the data set

# Q7 Trend analysis
sales_by_date = df.groupby('Order Date')['Sales'].sum()
plt.figure(figsize=(10,10))
sales_by_date.plot(kind = 'line', title='Sales by date',color = colors[1])
# peaked year: 2014 INSIGHT
# Determine product category with most growth:
category_growth = df.groupby('Category')['Sales'].sum().sort_values(ascending=False)
plt.figure(figsize=(10,10))
category_growth.plot(kind = 'line', title='Category Growth',color = colors[1])

# Q7 Customer Analysis:
# Identify top 5 customers:
top_customers = df.groupby('EmailID')['Sales'].sum().nlargest(5)
top_customers

# Analyze repeat purchase behavior:
repeat_purchase = df.groupby('EmailID')['Order Date'].diff().mean()
repeat_purchase
# insight: customers buy in the time frame of 3 days

"""Q7
Comprehensive Analytics:
1. Analyzing sales velocity data can help forecast demand more accurately, allowing suppliers to minimize stockouts and excess inventory, so optimizing storage levels and costs.
It will also help the suppliers plan production according therby reducing wastage and errors.

2. We can analyze sales data by region and hence find out the unique nature of movement of product for each locality and thereby focusing on target marketing for each individual region/locality, this will increase sales. We can also identify regions for higher revenue and potential customers in certain regions.


3. We can identify patterns of high value customers by analyzing their data and what influences them to buy it - (value or quality or brand name or aesthetics or fashion or because of a targeted ad)
We can then send out marketing messages and promotions to these high value customers and even give them good offers and attractive gifts to retain them. We can also strengthen customer relationships and inform them of any sale or offer currently going on and encourage them to repeat their purchases.
We should also provide these high value customers exceptional customer service.

"""